//Artists I've seen in festivals
const collection = [
    {
      artist: "Muse",
      festival: "Rock Werchter",
      year: 2000,
      originalMembers: [
        "Matthew Bellamy",
        "Christopher Wolsenholme",
        "Dominic Howard",
      ],
      lastAlbum: "link to Will of the People (2022)",
      photo: "image",
    },
    {
        artist: "Les Wampas",
        festival: "Francofolies de Spa",
        year: 2007,
        originalMembers: [
          "Didier Wampas",
          "Jean-Michel Lejoux",
          "Effello",
          "Nicolas Schauer",
          "Tony Truant",
        ],
        lastAlbum: "link to Tempête, Tempête (2022)",
        photo: "image",
      },
    {
        artist: "Nick Cave",
        festival: "Rock Werchter",
        year: 2011,
        originalMembers: "Nick Cave",
        lastAlbum: "link to Carnage (2021)",
        photo: "image",
      },
      {
        artist: "The Who",
        festival: "Lokerse Feesten",
        year: 2011,
        originalMembers: [
          "Roger Daltrey",
          "Pete Townshend",
          "Keith Moon",
          "John Entwistle",
        ],
        lastAlbum: "link to Who (2019)",
        photo: "image",
      },
      {
        artist: "The Beach Boys",
        festival: "Lokerse Feesten",
        year: 2012,
        originalMembers: [
          "Brian Wilson",
          "Dennis Wilson",
          "Carl Wilson",
          "Mick Love",
          "Al Jardine",
        ],
        lastAlbum: "link to That's why God made the Radio (2018)",
        photo: "image",
      },
      {
        artist: "The Dandy Warhols",
        festival: "Le Cabaret Vert",
        year: 2012,
        originalMembers: [
          "Courtney Taylor-Taylor",
          "Zia McCabe",
          "Peter Holmström",
          "Brent De Boer",
        ],
        lastAlbum: "link to Why you so crazy (2022)",
        photo: "image",
      },
      {
        artist: "Thomas Fersen",
        festival: "LaSemo",
        year: 2012,
        originalMembers: [
          "Thomas Fersen",
        ],
        lastAlbum: "link to C'est tout ce qu'il me reste (2019)",
        photo: "image",
      },
      {
        artist: "Henri Dès",
        festival: "Les Solidarités",
        year: 2014,
        originalMembers: [
          "Henri Dès",
        ],
        lastAlbum: "link to Casse-pieds (2013)",
        photo: "image",
      },
      {
        artist: "Jack Johnson",
        festival: "Rock Werchter",
        year: 2014,
        originalMembers: [
          "Jack Johnson",
        ],
        lastAlbum: "link to Meet the Moonlight (2022)",
        photo: "image",
      },
      {
        artist: "Queens of the Stone Age",
        festival: "Pukkelpop",
        year: 2014,
        originalMembers: [
          "Josh Homme",
          "Troy Van Leeuwen",
          "Dean Fertita",
          "Michael Shuman",
          "Jon Theodore",
        ],
        lastAlbum: "link to Villains (2017)",
        photo: "image",
      },
  ];